# -*- coding: utf-8 -*-
"""Homework2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXhI-d14WwVshEdzCR416FloXogMcnxu
"""

import numpy as np
A=np.array([[2,-6,-1],[-3,-1,7],[-8,1,-2]])
B=np.array([-38,-34,-20])
x=np.linalg.solve(A,B)
print(x)